### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by sunshineclt** [KyriacosShiarli/IRLF_aamas2016_Replicate#1]
I try to clone and run it on my computer but I got this error: 
Traceback (most recent call last):
  File "experiments.py", line 178, in <module>
    experiment_overlapping(name = "overlapping",steps =15,iterations_per_run= 40,runs = 2)
  File "experiments.py", line 95, in experiment_overlapping
    expert2 = Model(disc,"obstacle2_reach", load_saved = False)
  File "/home/sunshine/Programming/Github/IRLF_aamas2016_Replicate/gridworld/tp_Model.py", line 33, in __init__
    self.buildFeatureFunction()
  File "/home/sunshine/Programming/Github/IRLF_aamas2016_Replicate/gridworld/tp_Model.py", line 113, in buildFeatureFunction
    features = self.disc.quantityToFeature(state_quantity,action_quantity) #Still hacky. Need to find a solution to his
  File "/home/sunshine/Programming/Github/IRLF_aamas2016_Replicate/gridworld/tp_discretisationmodel.py", line 76, in quantityToFeature
    feature = self.feature(state,self.target,self.boundaries)
  File "/home/sunshine/Programming/Github/IRLF_aamas2016_Replicate/gridworld/tp_RFeatures.py", line 12, in toy_problem_simple
    xtar[dist]=1
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Can you please tell me your python and other environment? 
Thank you very much!

**Comment by sunshineclt** [comment]
I've figured it out: You need to add int() outside the abs() to transform it from float to integer:)

**Comment by KyriacosShiarli** [comment]
Thats true. I dont know why numpy never gave me an error about that in the past. I will push the correction. Also there is one experiment in experiments.py that you will not need namely the experiment cvx contrasting. 

You will also need a directory called saved where the source is. I will also push these corrections

**Comment by sunshineclt** [comment]
Thank you very much:)

**Comment by sunshineclt** [comment]
@KyriacosShiarli I think you also need to delete the line 182 in experiments.py: `plot_results("cvx_contrasting","results/aamas",2)`. Otherwise it will throw a runtime error about not finding the result since you comment line 181.
